models/StartMaxPrice.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "start_max_price".
 *
 * @property int $id
 * @property int $contract_start_max_price НМЦК | Начальная Максимальная Цена Контракта:
 * @property int $oz ОЗ | Обеспечения Заявки: от НМЦК
 * @property int $oz_percent ОЗ | Обеспечения Заявки: %
 * @property int $oik_mck ОИК | Обеспечение Исполнения Контракта: от МЦК
 * @property int $oik_contract ОИК | Обеспечение Исполнения Контракта: от Контракта
 * @property int $oik_percent ОИК | Обеспечение Исполнения Контракта: %
 * @property int $ogo_mck ОГО | Обеспечение Гарантийных Обязательств: от МЦК
 * @property int $ogo_contract ОГО | Обеспечение Гарантийных Обязательств: от Контракта
 * @property int $ogo_percent ОГО | Обеспечение Гарантийных Обязательств: %
 * @property int $contract_id id контракта
 * @property string $created_at дата созданя
 * @property string $updated_at дата изменения
 * @property integer $oik_type
 * @property integer $ogo_type
 * @property integer $bidSum
 * @property integer $profit
 * @property integer $productCoast
 * @property integer $profitPercent
 * @property integer $decline
 * @property int $oz_bg БГ
 * @property int $oik_bg БГ
 * @property int $ogo_bg БГ
 *
 *
 * @property Contract $contract
 */
class StartMaxPrice extends \yii\db\ActiveRecord
{
    public $bidSum;
    public $decline;
    public $productCoast;
    public $profitPercent;
    public $profit;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'start_max_price';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['contract_id','oik_type','ogo_type','decline'], 'integer'],
            [['created_at', 'oik_mck', 'ogo_mck','oik_contract','ogo_contract', 'updated_at','bidSum','productCoast','profitPercent','profit','oz_percent','ogo_percent','oik_percent', 'oz_bg', 'oik_bg', 'ogo_bg'], 'safe'],
            [['contract_start_max_price','oz'], 'double'],
            [['bidSum','contract_start_max_price'],'required'],
            [['contract_id'], 'exist', 'skipOnError' => true, 'targetClass' => Contract::className(), 'targetAttribute' => ['contract_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'contract_start_max_price' => 'НМЦК | Начальная Максимальная Цена Контракта:',
            'oz' => 'ОЗ | Обеспечения Заявки: от НМЦК',
            'oz_percent' => 'ОЗ | Обеспечения Заявки: %',
            'oik_mck' => 'ОИК | : от НМЦК',
            'oik_contract' => 'ОИК |: от Контракта',
            'oik_percent' => 'ОИК |: %',
            'ogo_mck' => 'ОГО | : от НМЦК',
            'ogo_contract' => 'ОГО | : от Контракта',
            'ogo_percent' => 'ОГО | : %',
            'contract_id' => 'id контракта',
            'created_at' => 'дата созданя',
            'updated_at' => 'дата изменения',
            'bidSum' => 'Сумма Торгов',
            'productCoast' => 'Стоимость товара',
            'profitPercent' => 'Прибыль в %',
            'profit' => 'Прибыль',
            'oik_type' => 'Тип ОИК',
            'ogo_type' => 'Тип ОГО',
            'oz_bg' => 'БГ',
            'oik_bg' => 'БГ',
            'ogo_bg' => 'БГ'
        ];
    }
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => 'updated_at',
                'createdAtAttribute' => 'created_at',
                'value' => date('Y-m-d H:i:s'),
            ],

        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContract()
    {
        return $this->hasOne(Contract::className(), ['id' => 'contract_id']);
    }

    public function beforeSave($insert)
    {
        if ($this->bidSum != null){
            $decline = 100 - (($this->bidSum/$this->contract_start_max_price)*100);
            $bid = Bidding::find()->where(['contract_id' => $this->contract_id])->one();
            $bid->bid_sum = $this->bidSum;
            $bid->decline = $decline<25?0:1;
            $bid->save();
        }

        if($this->oz_bg){
            $this->oz = 0;
        }


        if($this->oik_bg){
            $this->oik_contract = 0;
        }

        if($this->ogo_bg){
            $this->ogo_contract = 0;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     * @return StartMaxPriceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new StartMaxPriceQuery(get_called_class());
    }
}

controllers/StartMaxPriceController.php
<?php

namespace app\controllers;

use app\models\CostsSearch;
use Yii;
use app\models\StartMaxPrice;
use app\models\StartMaxPriceSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * StartMaxPriceController implements the CRUD actions for StartMaxPrice model.
 */
class StartMaxPriceController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all StartMaxPrice models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new StartMaxPriceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $costsSearchModel = new CostsSearch();
        $costsDataProvider = $costsSearchModel->search([]);
        $costsDataProvider->query->andWhere(['contract_id' => $searchModel->contract_id]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'costsSearchModel' => $costsSearchModel,
            'costsDataProvider' => $costsDataProvider,
        ]);
    }


    /**
     * Displays a single StartMaxPrice model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "StartMaxPrice #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Edit',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new StartMaxPrice model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($contract_id,$containerPjaxReload = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $model = new StartMaxPrice();
        $model->contract_id = $contract_id;

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавть НМЦК",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Добавить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>$containerPjaxReload,
                    'title'=> "Добавление НМЦК",
                    'content'=>'<span class="text-success">Добавлено успешно</span>',
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Добавить еще',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])
        
                ];         
            }else{           
                return [
                    'title'=> "Добавить НМЦК",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Добавить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    /**
     * Updates an existing StartMaxPrice model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id,$containerPjaxReload = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить НМЦК #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>$containerPjaxReload,
                    'forceClose'=>true
                   ];
            }else{
                 return [
                    'title'=> "Изменить НМЦК #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['contract/view', 'id' => $model->contract_id, 'forceReload'=>$containerPjaxReload,
                    'forceClose'=>true]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing StartMaxPrice model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id,$containerPjaxReload = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>$containerPjaxReload];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

     /**
     * Delete multiple existing StartMaxPrice model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBulkDelete()
    {        
        $request = Yii::$app->request;
        $pks = explode(',', $request->post( 'pks' )); // Array or selected records primary keys
        foreach ( $pks as $pk ) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
       
    }

    /**
     * Finds the StartMaxPrice model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return StartMaxPrice the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = StartMaxPrice::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/start-max-price/_columns.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
//    [
//        'class' => 'kartik\grid\SerialColumn',
//        'width' => '30px',
//    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'contract_start_max_price',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'oz',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'oz_percent',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'oik_mck',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'oik_contract',
    ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'oik_percent',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ogo_mck',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ogo_contract',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ogo_percent',
     ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'contract_id',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'created_at',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'updated_at',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label' => 'Скачать',
        'content' => function($model){
            return Html::a('<i class="fa fa-pencil text-success" style="font-size: 16px;"></i>', ['start-max-price/update', 'id' => $model->id, 'containerPjaxReload' => '#pjax-container-info-container'], ['role' => 'modal-remote'])
                .' '.Html::a('<i class="fa fa-trash text-danger" style="font-size: 16px;"></i>', ['start-max-price/delete', 'id' => $model->id, 'containerPjaxReload' => '#pjax-container-info-container'],[
                    'role'=>'modal-remote','title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-toggle'=>'tooltip',
                    'data-confirm-title'=>'Вы уверены?',
                    'data-confirm-message'=>'Вы действительно хотите удалить файл'
                ]);
        }
    ],

];   

views/start-max-price/_form.php
<?php

use app\models\Bidding;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\StartMaxPrice */
/* @var $form yii\widgets\ActiveForm */
$contract_id = $model->contract_id;
if($model->isNewRecord == false) {
    $bidding = Bidding::find()->where(['contract_id' => $model->contract_id])->one();
    $model->bidSum = $bidding->bid_sum;
    $model->productCoast = $bidding->product_cost;
    $model->profit = $bidding->profit;
    $model->profitPercent = $bidding->profit_percent;
    $model->decline = $bidding->decline;

}
$onChangeOik = <<<JS
        let checkVal = $(this).find('input:checked').val();
        if (checkVal == 0){
           
            document.getElementById("oik_type_contract").hidden=false; 
            document.getElementById("oik_type_mck").hidden=true; 
        }
       if (checkVal == 1){
            document.getElementById("oik_type_contract").hidden=true; 
            document.getElementById("oik_type_mck").hidden=false;  
        }
JS;
$onChangeOgo = <<<JS
        let checkVal = $(this).find('input:checked').val();
        if (checkVal == 0){
           
            document.getElementById("ogo_type_contract").hidden=false; 
            document.getElementById("ogo_type_mck").hidden=true; 
        }
       if (checkVal == 1){
            
            document.getElementById("ogo_type_contract").hidden=true; 
            document.getElementById("ogo_type_mck").hidden=false;  
        }
JS;
$ozPercent = <<<JS
        let percentVal = $(this).val();
        let nmckVal = document.getElementById("startmaxprice-contract_start_max_price").value;
        let ozVal = nmckVal/100*percentVal;
        document.getElementById("startmaxprice-oz").value = ozVal;
JS;
$ozNmck = <<<JS
        let ozNmckVal = $(this).val();
        let nmckVal = document.getElementById("startmaxprice-contract_start_max_price").value;
        let percentVal = ozNmckVal*100/nmckVal;
        document.getElementById("startmaxprice-oz_percent").value = percentVal.toFixed(2);
JS;
$oikContract = <<<JS
        let oikVal = $(this).val();
        let bidVal = document.getElementById("startmaxprice-bidsum").value;
        let percentVal = oikVal*100/bidVal;
        document.getElementById("startmaxprice-oik_percent").value = percentVal.toFixed(2);
JS;
$oikNmck = <<<JS
        let oikVal = $(this).val();
        let nmckVal = document.getElementById("startmaxprice-contract_start_max_price").value;
        let percentVal = oikVal*100/nmckVal;
        document.getElementById("startmaxprice-oik_percent").value = percentVal.toFixed(2);
JS;
$oikPercent = <<<JS
        let oikPercentVal = $(this).val();
        let bidVal = document.getElementById("startmaxprice-bidsum").value;
        let nmckVal = document.getElementById("startmaxprice-contract_start_max_price").value;
        let sumBid = bidVal/100*oikPercentVal;
        let sumNmck = nmckVal/100*oikPercentVal;
        
        document.getElementById("startmaxprice-oik_contract").value = sumBid;
        document.getElementById("startmaxprice-oik_mck").value = sumNmck;
JS;
$ogoContract = <<<JS
       let ogoVal = $(this).val();
        let bidVal = document.getElementById("startmaxprice-bidsum").value;
        let percentVal = ogoVal*100/bidVal;
        document.getElementById("startmaxprice-ogo_percent").value = percentVal.toFixed(2);
JS;
$ogoNmck = <<<JS
        let ogoVal = $(this).val();
        let nmckVal = document.getElementById("startmaxprice-contract_start_max_price").value;
        let percentVal = ogoVal*100/nmckVal;
        document.getElementById("startmaxprice-ogo_percent").value = percentVal.toFixed(2);
JS;
$ogoPercent = <<<JS
        let ogoPercentVal = $(this).val();
        let bidVal = document.getElementById("startmaxprice-bidsum").value;
        let nmckVal = document.getElementById("startmaxprice-contract_start_max_price").value;
        let sumBid = bidVal/100*ogoPercentVal;
        let sumNmck = nmckVal/100*ogoPercentVal;
        
        document.getElementById("startmaxprice-ogo_contract").value = sumBid;
        document.getElementById("startmaxprice-ogo_mck").value = sumNmck;
JS;
$bidtype = <<<JS
        let bidVal = $(this).val();
        let nmckVal = document.getElementById("startmaxprice-contract_start_max_price").value;
        let perc = 100 - ((bidVal/nmckVal)*100);
        if (perc < 25){
            document.getElementById("decline").hidden=true;
                let oikPercentVal = document.getElementById("startmaxprice-oik_percent").value;
                let ogoPercentVal = document.getElementById("startmaxprice-ogo_percent").value;
                let oikVal = bidVal/100*oikPercentVal;
                let ogoVal = bidVal/100*ogoPercentVal;
                document.getElementById("startmaxprice-ogo_contract").value = ogoVal;
                document.getElementById("startmaxprice-oik_contract").value = oikVal;
        }
        if (perc > 25){
            document.getElementById("decline").hidden=false; 
            let oikPercentVal = document.getElementById("startmaxprice-oik_percent").value;
            let ogoPercentVal = document.getElementById("startmaxprice-ogo_percent").value;
            let oikVal = bidVal/100*oikPercentVal;
            let ogoVal = bidVal/100*ogoPercentVal;
            oikVal = oikVal + (oikVal/2);
            ogoVal = ogoVal + ((ogoVal/2));
            
            document.getElementById("startmaxprice-ogo_contract").value = ogoVal;
            document.getElementById("startmaxprice-oik_contract").value = oikVal;
            
        }
JS;
?>

<div class="start-max-price-form">

    <?php $form = ActiveForm::begin([
        'method' => 'post',
        'action' => ['start-max-price/update','id' => $model->id,'containerPjaxReload' => $containerPjaxReload ],
    ]); ?>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <h4 class="panel-title">Начальная и максимальная цена контракта</h4>
                </div>
                <div class="panel-body" style="height: 350px; overflow-y: auto;">
                    <div class="row"style="margin-top: 5px">
                        <div class="col-md-3">
                            <?= $form->field($model, 'contract_start_max_price')->textInput()->label('НМЦК') ?>
                        </div>
                        <div class="col-md-3">
                            <?= $form->field($model, 'oz')->textInput([
                                'onChange' => $ozNmck
                            ])->label('ОЗ') ?>
                        </div>
                        <div class="col-md-3">
                            <?= $form->field($model, 'oz_percent')->textInput([
                                'onChange' => $ozPercent
                            ])->label('ОЗ %') ?>
                        </div>
                        <div class="col-md-3">
                            <?= $form->field($model, 'oz_bg')->checkbox(['style' => 'margin-top: 30px;']) ?>
                        </div>

                    </div>
                    <div class="row"style="margin-top: 5px">
                        <div class="col-md-3">
                            <?= $form->field($model, 'oik_type')->radioList([
                                0 =>'от Контратка',
                                1 => 'от НМЦК'
                            ],['id' => 'oik_type','onchange' => $onChangeOik]

                            )?>
                        </div>
                        <div class="col-md-3"id="oik_type_contract" <?php if ($model->oik_type == 1 ) echo 'hidden'?>>
                            <?= $form->field($model, 'oik_contract')->textInput([
                                'onchange' => $oikContract
                            ]) ?>
                        </div>
                        <div class="col-md-3"id="oik_type_mck" <?php if ($model->oik_type == 0) echo 'hidden'?>>
                            <?= $form->field($model, 'oik_mck')->textInput([
                                'onchange' => $oikNmck
                            ]) ?>
                        </div>
                        <div class="col-md-3">
                            <?= $form->field($model, 'oik_percent')->textInput([
                                'onchange' => $oikPercent
                            ]) ?>
                        </div>
                        <div class="col-md-3">
                            <?= $form->field($model, 'oik_bg')->checkbox(['style' => 'margin-top: 30px;']) ?>
                        </div>
                    </div>
                    <div class="row"style="margin-top: 5px">
                        <div class="col-md-3">
                            <?= $form->field($model, 'ogo_type')->radioList([
                                0 =>'от Контратка',
                                1 => 'от НМЦК'
                            ],['id' => 'oik_type','onchange' => $onChangeOgo]

                            )?>
                        </div>
                        <div class="col-md-3"id="ogo_type_contract" <?php if ($model->ogo_type == 1 ) echo 'hidden'?>>
                            <?= $form->field($model, 'ogo_contract')->textInput([
                                 'onchange' => $ogoContract
                            ]) ?>
                        </div>
                        <div class="col-md-3"id="ogo_type_mck" <?php if ($model->ogo_type == 0) echo 'hidden'?>>
                            <?= $form->field($model, 'ogo_mck')->textInput([
                                'onchange' => $ogoNmck
                            ]) ?>
                        </div>
                        <div class="col-md-3">
                            <?= $form->field($model, 'ogo_percent')->textInput([
                                'onchange' => $ogoPercent
                            ]) ?>
                        </div>
                        <div class="col-md-3">
                            <?= $form->field($model, 'ogo_bg')->checkbox(['style' => 'margin-top: 30px;']) ?>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-6">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <h4 class="panel-title">Сумма контракта</h4>
                </div>
                <div class="panel-body" style="height:170px; overflow-y: visible;">
                    <div class="row">
                        <div class="col-md-6">
                            <?= $form->field($model, 'bidSum')->textInput([
                                'onchange' => $bidtype
                            ]) ?>
                        </div>
                        <div class="col-md-6"id="decline"<?php if ($model->decline == 0) echo 'hidden'?>>
                            <div class="dec-wrap"style="background-color: lightcoral;border-radius:15px;">
                                <h4 style="margin: 5px;">Снижение > 25%</h4>
                                <p style="margin: 5px 0px 5px 10px;color: white;">
                                    Думай всегда
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <?= $form->field($model, 'productCoast')->textInput() ?>
                        </div>
                        <div class="col-md-4">
                            <?= $form->field($model, 'profit')->textInput() ?>
                        </div>
                        <div class="col-md-4">
                            <?= $form->field($model, 'profitPercent')->textInput() ?>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-6">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <h4 class="panel-title">Дополнительные расходы</h4>
                    <div class="panel-heading-btn" style="margin-top:-20px;overflow-y: auto;">
                        <?= Html::a('<span class="glyphicon glyphicon-plus btn-circle"></span>', ['costs/create', 'contract_id' => $contract_id, 'containerPjaxReload' => $containerPjaxReload],
                            ['role'=>'modal-remote','title'=> 'Добавить Дополнительные расходы','class'=>'btn btn-warning btn-xs'])?>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning"  data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    </div>
                </div>
                <div class="panel-body" style=" overflow-y: auto;">
                    <?= $this->render('@app/views/costs/index',[
                        'searchModel' => $costsSearchModel,
                        'dataProvider' => $costsDataProvider,
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
    </div>



    <?php if (!Yii::$app->request->isAjax){ ?>
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Изменть', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    <?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/start-max-price/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\StartMaxPrice */

?>
<div class="start-max-price-create">
    <?= $this->render('_form', [
        'model' => $model,

    ]) ?>
</div>