models/Customer.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "customer".
 *
 * @property int $id
 * @property string $inn ИНН
 * @property string $kpp КПП
 * @property string $full_name Полное наименование организаци
 * @property string $short_name Сокращенное наименование организаци
 * @property string $shipping_address Адрес доставки
 * @property string $delivery_date Срок поставки
 * @property string $pay_date Срок оплаты
 * @property string $lot_link Ссылка на Лот в системе поиска аукционов
 * @property string $lot_link_playground Ссылка на лот в на площадке
 * @property string $lot_link_portal Ссылка на лот на портале госзакупок
 * @property string $conducting_way Способ проведения
 * @property string $deadline Окончание сбора заявок
 * @property string $bid_consideration Рассмотрение заявок
 * @property string $auction_date Проведение аукциона
 * @property string $created_at дата созданя
 * @property string $updated_at дата изменения
 * @property string $for_small_business дата изменения
 * @property string $purchase_name Наименование закупки
 * @property integer $date_type Тип Срока поставки
 * @property integer $delivery_days доставка днейlot_link_playground
 * @property integer $pay_days оплата дней
 * @property integer $pay_type Тип оплаты
 * @property string $link_1s ссылка 1с
 *
 *
 *

 */
class Customer extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'customer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pay_days','date_type','delivery_days','pay_type'],'integer'],
            [[
                'auction_date',
                'bid_consideration',
                'deadline',
                'conducting_way',
                'shipping_address',
                'full_name',
                'short_name',
                'inn',
                'kpp',
            ], 'required'],
            [['delivery_date', 'pay_date', 'deadline', 'bid_consideration', 'auction_date', 'created_at', 'updated_at','for_small_business','purchase_name','link_1s'], 'safe'],
            [['inn', 'kpp', 'full_name', 'short_name', 'shipping_address', 'lot_link', 'lot_link_playground', 'lot_link_portal', 'conducting_way'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'inn' => 'ИНН',
            'kpp' => 'КПП',
            'full_name' => 'Полное наименование организации',
            'short_name' => 'Сокращенное наименование организации',
            'shipping_address' => 'Адрес доставки',
            'delivery_date' => 'Срок поставки',
            'pay_date' => 'Срок оплаты',
            'lot_link' => 'Ссылка на Лот в системе поиска аукционов',
            'lot_link_playground' => 'Ссылка на лот в на площадке',
            'lot_link_portal' => 'Ссылка на лот на портале госзакупок',
            'conducting_way' => 'Способ проведения',
            'deadline' => 'Окончание сбора заявок',
            'bid_consideration' => 'Рассмотрение заявок',
            'auction_date' => 'Проведение аукциона',
            'created_at' => 'дата созданя',
            'updated_at' => 'дата изменения',
            'for_small_business' => 'Для субъекта малого предпринимательства',
            'purchase_name' => 'Наименование закупки',
            'date_type' => 'Тип Срока поставки',
            'pay_days' => 'Срок оплаты',
            'delivery_days' =>'Срок поставки',
            'pay_type' => 'Тип оплаты',
            'link_1s' => 'Ссылка на 1с'

        ];
    }
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => 'updated_at',
                'createdAtAttribute' => 'created_at',
                'value' => date('Y-m-d H:i:s'),
            ],

        ];
    }
    /**
     * @return string
     */
    public function getFullName() {
        return $this->full_name . ' ' . $this->short_name . ' ' . $this->inn;
    }

    /**
     * @inheritdoc
     * @return CustomerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CustomerQuery(get_called_class());
    }
}

controllers/CustomerController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Customer;
use app\models\CustomerSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * CustomerController implements the CRUD actions for Customer model.
 */
class CustomerController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Customer models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new CustomerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Customer model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {

        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Customer #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Edit',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new Customer model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($contract_id,$containerPjaxReload = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $model = new Customer();
        $model->contract_id = $contract_id;

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить заказчика",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Добавить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>$containerPjaxReload,
                    'title'=> "Добавление заказчика",
                    'content'=>'<span class="text-success">Добавлено успешно</span>',
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Добавить еще',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])
        
                ];         
            }else{           
                return [
                    'title'=> "Добавить заказчика",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Добавить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    /**
     * Updates an existing Customer model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id,$containerPjaxReload = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить заказчика #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];
            }else if($model->load($request->post()) && $model->save()){
                  return [
                    'forceReload'=>$containerPjaxReload,
                    'forceClose'=>true
                   ];
            }else{
                return [
                    'title'=> "Изменить заказчика #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Изменить',['class'=>'btn btn-primary','type'=>"submit"])
                ];
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['contract/view', 'id' => $model->contract_id, 'forceReload'=>$containerPjaxReload,
                    'forceClose'=>true]);

            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing Customer model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id,$containerPjaxReload = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>$containerPjaxReload];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

     /**
     * Delete multiple existing Customer model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBulkDelete()
    {        
        $request = Yii::$app->request;
        $pks = explode(',', $request->post( 'pks' )); // Array or selected records primary keys
        foreach ( $pks as $pk ) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
       
    }

    /**
     * Finds the Customer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Customer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Customer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/customer/_columns.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
//    [
//        'class' => 'kartik\grid\SerialColumn',
//        'width' => '30px',
//    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'inn',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'kpp',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'full_name',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'short_name',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'shipping_address',
    ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'delivery_date',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'pay_date',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'lot_link',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'lot_link_playground',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'lot_link_portal',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'conducting_way',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'deadline',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'bid_consideration',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'auction_date',
     ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'created_at',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'updated_at',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label' => 'Скачать',
        'content' => function($model){
            return Html::a('<i class="fa fa-pencil text-success" style="font-size: 16px;"></i>', ['customer/update', 'id' => $model->id, 'containerPjaxReload' => '#pjax-container-info-container'], ['role' => 'modal-remote'])
                .' '.Html::a('<i class="fa fa-trash text-danger" style="font-size: 16px;"></i>', ['customer/delete', 'id' => $model->id, 'containerPjaxReload' => '#pjax-container-info-container'],[
                    'role'=>'modal-remote','title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-toggle'=>'tooltip',
                    'data-confirm-title'=>'Вы уверены?',
                    'data-confirm-message'=>'Вы действительно хотите удалить файл'
                ]);
        }
    ],

];   

views/customer/_form.php
<?php

use kartik\date\DatePicker;
use kartik\datetime\DateTimePicker;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Customer */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="customer-form">

    <?php $form = ActiveForm::begin([
        'method' => 'post',
        'action' => ['customer/update','id' => $model->id,'containerPjaxReload' => $containerPjaxReload ],
    ])?>
    <div class="row">
        <div class="col-md-2">
            <?= $form->field($model, 'purchase_name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'date_type')->
            dropDownList([
                    '8' => 'не задано',
                    '3' => 'Рабочих дней',
                    '1' => 'Календарных дней',
                    '2' => 'Выбор даты',
               ],
                ['id'=>'date_type', 'onChange'=>'$(document).ready(function() {
                        if ( document.getElementById("date_type").value == "3") {
                              document.getElementById("date_in").hidden=false; 
                            document.getElementById("date_out").hidden=true; 
                        }
                        if ( document.getElementById("date_type").value == "1") {
                            document.getElementById("date_in").hidden=false; 
                            document.getElementById("date_out").hidden=true;  
                        }
                        if ( document.getElementById("date_type").value == "2") {
                            document.getElementById("date_in").hidden=true; 
                            document.getElementById("date_out").hidden=false; 
                        }
                         if ( document.getElementById("date_type").value == "8") {
                            document.getElementById("date_in").hidden=true; 
                            document.getElementById("date_out").hidden=true; 
                        }     
                    });']) ?>
        </div>

        <div class="col-md-1"id="date_in" <?php if ($model->date_type == 2 or $model->date_type == null or $model->date_type == 8) echo 'hidden'?>>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model,'delivery_days')->textInput() ?>
                </div>
            </div>
        </div>
        <div class="col-md-2"id="date_out" <?php if ($model->date_type == 3 or $model->date_type == 1 or $model->date_type == null or $model->date_type == 8) echo 'hidden'?>>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model,'delivery_date')->widget(
                        DatePicker::className(),[
                            'options' => ['placeholder' => 'Выберите дату ...'],
                            'pluginOptions' => [
                                'format' => 'yyyy-mm-dd',
                                'todayHighlight' => true
                            ]
                        ]
                    ) ?>
                </div>
            </div>
        </div>



        <div class="col-md-2">
            <?= $form->field($model, 'pay_type')->dropDownList([
                '8' => 'не задано',
                '3' => 'Рабочих дней',
                '1' => 'Календарных дней',
                '2' => 'Выбор даты',
            ],['id'=>'pay_type', 'onChange'=>'$(document).ready(function() {
                        if ( document.getElementById("pay_type").value == "3") {
                            document.getElementById("pay_in").hidden=false; 
                            document.getElementById("pay_out").hidden=true; 
                        }
                        if ( document.getElementById("pay_type").value == "1") {
                            document.getElementById("pay_in").hidden=false; 
                            document.getElementById("pay_out").hidden=true;  
                        }
                        if ( document.getElementById("pay_type").value == "2") {
                            document.getElementById("pay_in").hidden=true; 
                            document.getElementById("pay_out").hidden=false; 
                        } 
                         if ( document.getElementById("pay_type").value === "8") {
                            document.getElementById("pay_in").hidden=true; 
                            document.getElementById("pay_out").hidden=true; 
                        }  
                    });']) ?>
        </div>

        <div class="col-md-1"id="pay_in" <?php if ($model->pay_type == 2 or $model->pay_type == null or $model->pay_type == 8) echo 'hidden'?>>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model,'pay_days')->textInput()?>
                </div>
            </div>
        </div>
        <div class="col-md-2"id="pay_out" <?php if ($model->pay_type == 3 or $model->pay_type == 1 or $model->pay_type == null or $model->pay_type == 8) echo 'hidden'?>>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model,'pay_date')->widget(
                        DatePicker::className(),[
                            'options' => ['placeholder' => 'Выберите дату ...'],
                            'pluginOptions' => [
                                'format' => 'yyyy-mm-dd',
                                'todayHighlight' => true
                            ]
                        ]
                    )?>
                </div>
            </div>
        </div>



    </div>




    <div class="row">
        <div class="col-md-2">
            <?= $form->field($model, 'inn')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'kpp')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'full_name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'short_name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'shipping_address')->textInput(['maxlength' => true]) ?>
        </div>

        <div class="col-md-2">
            <?= $form->field($model, 'lot_link')->textInput(['maxlength' => true]) ?>
        </div>


    </div>

    <div class="row">
        <div class="col-md-2">
            <?= $form->field($model, 'lot_link_playground')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'lot_link_portal')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'conducting_way')->widget(Select2::classname(), [
                'data' => [
                    'ЕП закупка единственного поставщка'  => 'ЕП закупка единственного поставщка',
                    'К конкурс' => 'К конкурс',
                    'А аукцион' => 'А аукцион',
                    'ЗП запрос предложений' => 'ЗП запрос предложений',
                    'ЗЦ запрос цен' => 'ЗЦ запрос цен',
                    'ЗК запрос котировок' => 'ЗК запрос котировок',
                    'ИС иной способ' => 'ИС иной способ',
                ],
                'language' => 'ru',
                'options' => ['placeholder' => 'выберите способ ...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]); ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model,'deadline')->widget(
                    DateTimePicker::className(),[
                            'options' => ['placeholder' => 'Выберите дату и время ...'],
                            'pluginOptions' => [
                                'format' => 'yyyy-mm-dd hh:ii',
                                'todayHighlight' => true
                            ]
                        ]
            )
           ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'bid_consideration')->widget(
                DatePicker::className(),[
                    'options' => ['placeholder' => 'Выберите дату ...'],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd',
                        'todayHighlight' => true
                    ]
                ]
            ) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model,'auction_date')->widget(
                DateTimePicker::className(),[
                    'options' => ['placeholder' => 'Выберите дату и время ...'],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd hh:ii',
                        'todayHighlight' => true
                    ]
                ]
            )
            ?>
        </div>

    </div>
    <div class="row">
        <div class="col-md-2">
            <?= $form->field($model, 'link_1s')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'for_small_business')->radioList([
                0 =>'СМП',
                1 => 'без СМП'
            ] )?>
        </div>
    </div>






  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Изменть', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>

</div>

views/customer/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Customer */

?>
<div class="customer-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/customer/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $candidateId integer */

CrudAsset::register($this);

?>
<?=GridView::widget([
    'id'=>'customer-datatable',
    'dataProvider' => $dataProvider,
//            'filterModel' => $searchModel,
    'pjax'=>true,
    'columns' => require(__DIR__.'/_columns.php'),

    'striped' => true,
    'condensed' => true,
    'responsive' => true,
//    'panel' => [
//        'headingOptions' => ['style' => 'display: none;'],
//        'after'=>'',
//    ]
])?>

views/customer/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Customer */
?>
<div class="customer-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/customer/view.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Customer */
?>
<div class="customer-view">
 
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
//            'id',
            'inn',
            'kpp',
            'full_name',
            'short_name',
            'shipping_address',
            'delivery_date',
            'pay_date',
            'lot_link',
            'lot_link_playground',
            'lot_link_portal',
            'conducting_way',
            'deadline',
            'bid_consideration',
            'auction_date',
            'created_at',
//            'updated_at',
        ],
    ]) ?>

</div>